---
title: "Maine Clinics"
author: "Christine Iyer"
date: "April 10, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

[For reference](http://rpubs.com/chrisiyer/221519)

```{r}
library(leaflet)
library(rgdal)
library(ggmap)
library(dplyr)
library(knitr)


City <- c("Bangor", "Belfast","Calais", "Damariscotta", "Dexter", "Ellsworth", "Farmington", "Fort Kent", "Houlton", "Lewiston", "Machias", "Norway", "Presque Isle",  "Rockland", "Rumford", "Skowhegan","Waterville", "Portland", "Biddeford", "Topsham", "Brownville" )

Clinics <- c(18, 1, 1, 1, 1,3,1, 19, 3, 10, 2,2,13,11,1,8,3, 0,0,0,0)

City <- as.character(City)
City <- paste(City, "Maine",sep = " ")

Location <- geocode(City[1:21])

Population <- c(33039, 6682,3123, 1142, 2158, 7741, 4288, 2488, 4856, 36592, 1274, 2748, 9692, 7297, 4218, 6297, 15722, 66194, 21277, 8800, 1200)

County <- c("Penobscot", "Waldo", "Washington", "Lincoln", "Penobscot", "Hancock", "Franklin", "Aroostook", "Aroostook", "Androscoggin", "Washington", "Oxford", "Aroostook","Knox", "Oxford", "Somerset", "Kennebec","Cumberland", "York", "Sagadahoc", "Piscataquis")
CNTYCODE <- as.factor(c("19", "27" ,"29"  , "15", "19" ,"09","07" ,"03" ,"03" ,"01" ,"29" ,"17","03" ,"13" ,"17" ,"25" ,"11" ,"05" ,"31" ,"23" ,"21" ))

Leahs <- cbind.data.frame(City, Clinics, Population, Location, County, CNTYCODE)
Leahs <- mutate(Leahs, City = gsub(" Maine", "", City))
kable(Leahs)
str(Leahs)
ClinicbyCounty <- Leahs %>% group_by(County) %>% summarise(sum(Clinics))
ClinicbyCounty
```

https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTaNgIjVruTY_rebXeXNgWuDQGMNrJ_rXaBZ0PIQzz-TCyzCcsddA

https://cdn4.iconfinder.com/data/icons/Gifts/128/bouquet.png

```{r}


IconHosp <- makeIcon(iconUrl = "https://cdn4.iconfinder.com/data/icons/Gifts/128/bouquet.png", iconWidth = 31*215/230, iconHeight = 31, iconAnchorX = 31*215/230/2, iconAnchorY = 16)


popupLabel <- paste(Leahs$City, " has ", Leahs$Clinics, " clinics\nfor your abortion pleasure")
```


```{r, eval=FALSE, include=FALSE}
New <- leaflet() %>% addTiles() %>% addMarkers(lng = Leahs$lon, lat = Leahs$lat, icon = IconHosp, popup = popupLabel) %>% setView(lng = -70.0589, lat = 43.3601, zoom = 6) %>% addProviderTiles("CartoDB.Positron")
New
```

```{r}
library(rgdal)
library(raster)
library(dplyr)
#setwd("/Users/Chris Iyer/Documents/county/")
me_counties <- me_counties <- readOGR("./county", "county")
kable(head(me_counties))
names(me_counties)
me_counties <- spTransform(me_counties, CRS("+proj=longlat +datum=WGS84"))
pal <- colorQuantile("Blues", NULL, n = 4)
```

```{r, echo=TRUE}
library(raster)
library(sp)
x <- sp::merge(me_counties, Leahs, by = 'CNTYCODE', duplicateGeoms = TRUE)
head(x)
dim(x)

pointsMap <- read.csv("NewMap.csv")
head(pointsMap)
```

```{r}
NewMap <- read.csv("NewMap.csv")
names(NewMap)

```


```{r, echo=TRUE}
#This is the map that works
y <- leaflet() %>% 
  addProviderTiles("CartoDB.PositronNoLabels") %>% 
  addPolygons(data = x, popup = ~popupLabel, fillColor = ~pal(x$Clinics), color = "##D46A6A", weight = 1) %>%  setView(lng = -70.0589, lat = 43.3601, zoom = 6) %>% addCircleMarkers(data = NewMap, lng = jitter(NewMap$lng), lat = jitter(NewMap$lat), color = "navy",
    stroke = FALSE, fillOpacity = 0.25)
y
```

```{r, eval=FALSE, include=FALSE}
pal1 <- qpal <- colorQuantile("Blues", x$Clinics, n = 4)


y <- leaflet() %>% 
  addProviderTiles("CartoDB.PositronNoLabels") %>% 
  addPolygons(data = x, popup = ~popupLabel, fillColor = ~pal1, color = "##D46A6A", weight = 1) %>%  setView(lng = -70.0589, lat = 43.3601, zoom = 6) %>% addCircleMarkers(data = NewMap, lng = jitter(NewMap$lng), lat = jitter(NewMap$lat))
y
```


